### ISSUE TITLE
Generate meaningful error messages for failed heat maps

### ISSUE THREAD

**Issue by enhaixie** [ybukhman/GCAT#70]
Server:
http://gcat-test.glbrc.org/assays/new

The steps to reproduce the issue:

see the attachments

![heat_map_1](https://cloud.githubusercontent.com/assets/15270031/14086707/181345da-f4ec-11e5-9b0e-63232424dd49.PNG)

![heat_map_2](https://cloud.githubusercontent.com/assets/15270031/14086711/1df32fba-f4ec-11e5-8acb-b7556669081e.PNG)

![heat_map_error](https://cloud.githubusercontent.com/assets/15270031/14086716/2667f856-f4ec-11e5-83db-24489305d829.PNG)

**Comment by ybukhman** [comment]
Thanks, Enhai, for pointing this out.  This is not a bug.  An error is supposed to be generated when specified heat map range does not overlap with the range of actual values of the corresponding statistic.  In this case, the range of actual values of _Achieved growth_ is 1.2 to 2.6 on log scale and 0.38 to 0.61 on linear scale.  However, the error message is confusing, because it says "spec.growth", which is not the statistic in question.  Additionally, it does not inform the user what the range of actual values is.  I suggest that the message should be changed to the following:
_Heat map range specified by user does not overlap with the actual range of [statistic].  The actual range is from [low bound] to [upper bound]_.

Substitute [words in square brackets] with appropriate values.

**Comment by amangpt777** [comment]
Thanks Enhai and Yury. 
Yury, I have sent the pull request to you. Please let me know if any issues.
